### ISSUE TITLE
Update Travis CI config

### ISSUE THREAD

**Issue by jimporter** [mkdocs/mkdocs-bootswatch-classic#1]
When preparing this repo, I didn't touch the `.travis.yml` config. Who's the right person to make these changes?

**Comment by d0ugal** [comment]
That might be me. What changes are needed?

**Comment by jimporter** [comment]
@d0ugal I think all that's needed is to enable this repo in the Travis CI interface and update the doc deployment bits here:

https://github.com/mkdocs/mkdocs-bootswatch-classic/blob/177fefa6ccadf76e825a3d0255a9cd36d4a9c23c/.travis.yml#L40

**Comment by waylan** [comment]
@d0ugal the deployment of `mkdocs-bootswatch` failed at the same stage (GitHub ages deployment) this past weekend. I didn't investigate why and just manually deployed the docs. But I wonder if perhaps the old GitHub token is no longer valid.

I also manually deployed the docs for `mkdocs-bootswatch-classic`. The only thing left to do is an actual release. Which PyPI account have the other projects been uploaded with? Whoever has control of that account will need to set up `mkdocs-bootswatch-classic` as well.

**Comment by d0ugal** [comment]
👍🏼 I’ll try and get to this as soon as I can. My second kid was born two days ago, so the timing couldn’t be much worse!

**Comment by jimporter** [comment]
@waylan @d0ugal Just wanted to get this back on your radar. No worries if you're too busy with other things though; this has definitely been a rough year!

**Comment by waylan** [comment]
@jimporter thanks for the reminder. We just switched mkdocs/mkdocs over to use GitHb actions. We should probably do the same here. And as I have full admin access now, I can do that myself. Just need to find some time to work on it. 😉

**Comment by jimporter** [comment]
Cool! That plus a release on PyPI and this project should be pretty much "done". I don't expect that there will be a lot of maintenance work required for it since the theme data is all self-contained in this repo now, so theme changes in mkdocs/mkdocs won't affect anything here.
