### ISSUE TITLE
Publish release on PyPI?

### ISSUE THREAD

**Issue by jimporter** [mkdocs/mkdocs-bootswatch-classic#2]
@waylan This might get resolved by #1, but for tracking purposes, I filed a separate issue.

It'd be nice to publish this package on PyPI so that people using the "classic" themes can use this easily (otherwise, you'd have to clone this repo to use them, or rely on a particular commit from mkdocs/mkdocs-bootswatch). I don't think there's a lot of need to provide further releases of this after the initial one though, since the themes are no longer derived from the default MkDocs theme. Barring any obscure bugs, there hopefully won't be much maintenance burden. :)

**Comment by waylan** [comment]
Sorry for the long delay in responding to this. In any event, the best way to move forward would be to add a GitHub workflow which automated publishing a release on a git tag, much like [this] upstream workflow.

**Comment by waylan** [comment]
As #4 has been merged. I now need to create the project on PYPI, generate a token, and save it to `secrets.PYPI_PASSWORD` here on GitHub.

As I understand it, to create the project, I will need to do a manual release first. Then I can create the token so that any future releases can be done automatically by pushing a tag.

**Comment by jimporter** [comment]
That sounds right. Based on the [twine docs](https://twine.readthedocs.io/en/stable/#twine-register), you *can* pre-register a package in theory, but it doesn't work on PyPI. So tagging and manually releasing the first version is the way to go, I think. (Hopefully there won't be a need for future releases, since this is a legacy project, but it's good to have the scaffolding set up.)

**Comment by waylan** [comment]
This has been released: https://pypi.org/project/mkdocs-bootswatch-classic/

Sorry for the long delay. But I did set up the token, so any future releases should be easier.
